Write new version
messerli-informatik-ag/code-style pull request #55
Opened 2020-12-09 15:05 UTC by flavios98

2020-12-09 15:09 UTC, bash requested changes

2020-12-09 15:09 UTC, bash commented on changelog.md
>  - Update StyleCop.Analyzers to 1.2.0-beta.312 ([diff](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/compare/1.2.0-beta.261...1.2.0-beta.312))
```suggestion
- Update StyleCop.Analyzers to 1.2.0-beta.312 ([diff](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/compare/1.2.0-beta.261...1.2.0-beta.312))
- Fix compilation error when building an F# project.
```

2020-12-10 07:02 UTC, flavios98 commented on changelog.md
>  - Update StyleCop.Analyzers to 1.2.0-beta.312 ([diff](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/compare/1.2.0-beta.261...1.2.0-beta.312))
https://github.com/messerli-informatik-ag/code-style/pull/55/commits/6f69d7988ccae16c28d49f16e38e27f74c65e025

2020-12-10 07:39 UTC, bash approved these changes

2020-12-10 07:41 UTC, merged